#!/usr/bin/env ruby

$LOAD_PATH << "lib"
require "month"
require "year"
require "zeller"

month = ARGV.first
year = ARGV.last

if ARGV[1]
  cal = Month.new(month.to_i, year.to_i)
  puts cal.to_s
else
  cal = Year.new(year.to_i)
  puts cal.to_s
end

